Fix fit entry parsing.
9elements/converged-security-suite pull request #224
Opened 2021-04-23 11:16 UTC by ChriMarMe

Fix for #223 

Signed-off-by: Christopher Meis <christopher.meis@9elements.com>

2021-04-23 11:50 UTC, xaionaro approved these changes
This is great :)

2021-04-23 11:50 UTC, xaionaro requested changes
Whoops, forgot to check one thing. Few minutes.

2021-04-23 12:51 UTC, xaionaro submitted a review, later dismissed

2021-04-23 12:53 UTC, xaionaro submitted a review, later dismissed

2021-04-23 12:59 UTC, xaionaro submitted a review, later dismissed

2021-04-26 08:40 UTC, walterchris commented on pkg/intel/metadata/fit/entry_headers.go
> +		panic("not implemented, yet")
is panic the right way to go here?

2021-04-27 11:51 UTC, xaionaro commented on pkg/intel/metadata/fit/entry_headers.go
> +		panic("not implemented, yet")
Fixed.

2021-04-27 11:52 UTC, xaionaro approved these changes

2021-04-27 11:54 UTC, walterchris submitted a review, later dismissed

2021-04-27 11:55 UTC, xaionaro approved these changes

2021-04-27 11:56 UTC, xaionaro commented
@walterchris : Fixed a commend and it dismissed your review decision. Could you repeat please? :)

2021-04-27 11:56 UTC, walterchris approved these changes
Sorry rebased too early - sorry for the noise.

2021-04-27 15:19 UTC, merged