Move AMD's MP0_C2P_MSG_37 to registers folder and add it to marshaller
9elements/converged-security-suite pull request #258
Opened 2021-06-29 16:23 UTC by rihter007

Fix PSP->PSB, PSB stands for Platform secure boot

2021-06-29 17:06 UTC, xaionaro commented on pkg/pcr/flow.go
> +	case "legacypsnenabled":
Looks like a typo (see `psn`).

2021-06-29 17:06 UTC, xaionaro requested changes
Please fix a typo

2021-06-29 17:07 UTC, rihter007 commented on pkg/pcr/flow.go
> +	case "legacypsnenabled":
Argh, thanks!

2021-06-29 17:07 UTC, xaionaro commented
Not approving, because fixing the typo will require re-approve. I'll try to approve as soon as the typo is fixed.

2021-06-29 17:35 UTC, xaionaro approved these changes

2021-06-30 07:05 UTC, ChriMarMe approved these changes

2021-06-30 07:05 UTC, merged