Add missing close to MSR register open fd
9elements/converged-security-suite pull request #264
Opened 2021-07-16 15:13 UTC by mimir-d

- there are usecases where this missing close leads to fd exhaustion

testing:
```
% go test   
PASS
ok  	github.com/9elements/converged-security-suite/v2/pkg/registers	0.289sw
```

2021-07-16 15:18 UTC, xaionaro requested changes
The linter is right, in this case we theoretically can get a panic.

Also may be it makes sense to put the whole content of the `for` to a separate function to avoid `defer`-ing in a loop. But this is a nitpicking. Feel free to ignore :)

2021-07-16 19:40 UTC, rihter007 commented
> The linter is right, in this case we theoretically can get a panic.
> 
> Also may be it makes sense to put the whole content of the `for` to a separate function to avoid `defer`-ing in a loop. But this is a nitpicking. Feel free to ignore :)


I guess once can use inplace function for it:

for i := 0; i < runtime.NumCPU(); i++ {
    func() {
       ...
       defer msr.Close()
       ...
    }()
}

2021-07-22 15:38 UTC, mimir-d commented
i could've sworn i put that defer after the error check. fixing...

2021-07-22 18:19 UTC, xaionaro submitted a review, later dismissed
Thanks!

2021-07-23 10:03 UTC, rihter007 submitted a review, later dismissed
LGTM, only one optional nit

2021-07-30 12:42 UTC, xaionaro approved these changes

2021-07-30 13:02 UTC, zaolin approved these changes

2021-07-30 13:02 UTC, merged