Add remaining cleanup and functionality
9elements/converged-security-suite pull request #350
Opened 2023-02-13 13:49 UTC by zaolin

Signed-off-by: Philipp Deppenwiese <zaolin.daisuki@gmail.com>

2023-02-13 15:41 UTC, flanfly requested changes

2023-02-13 15:41 UTC, flanfly commented on pkg/provisioning/bootguard/bootguard.go
>  		return nil, fmt.Errorf("either both or one manifest is nil")
Shouldn't that be `bpm == nil || km == nil`?

2023-02-13 15:41 UTC, flanfly commented on pkg/provisioning/bootguard/bootguard.go
> +		}
`>= 32`?

2023-02-13 15:41 UTC, flanfly commented on pkg/provisioning/bootguard/me.go
> +		return false, fmt.Errorf("force anchor boot is disabled")
That's Anchor Cove boot btw

2023-02-14 12:16 UTC, xaionaro approved these changes

2023-02-14 12:44 UTC, flanfly approved these changes

2023-02-14 12:45 UTC, merged