Add bg-suite tooling
9elements/converged-security-suite pull request #351
Opened 2023-02-14 12:56 UTC by zaolin

Signed-off-by: Philipp Deppenwiese <zaolin.daisuki@gmail.com>

2023-02-14 13:02 UTC, flanfly requested changes

2023-02-14 13:02 UTC, flanfly commented on cmd/bg-suite/README.md
> +**2. Execute the txt-suite.**
bg-suite

2023-02-14 13:23 UTC, xaionaro approved these changes

2023-02-15 10:02 UTC, walterchris approved these changes

2023-02-15 10:14 UTC, flanfly approved these changes

2023-02-15 11:27 UTC, merged